---
name: "Prod Image Build & Deployment"

on:
  push:
    branches:
      - prod

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      packer_version: "1.9.4"
    
    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Packer installation"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}

      - name: "Packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "Packer validate"
        run: packer validate -var-file="prod.pkrvars.hcl" .
        working-directory: ./packer/

      - name: "Format Packer Template"
        run: packer fmt .

      - name: "Packer build image"
        run: packer build -var-file="prod.pkrvars.hcl" . 
        working-directory: ./packer/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.PROD_REGION }}
